[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]



[[language]]
name = "c-sharp"
auto-format = true
formatter = {command = "bash", args = ["-c", "uncrustify -c $HOME/.config/helix/csharp.cfg --assume cs"] }



[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]



[[language]]
name = "xml"
file-types = ["xml", "lic", "slf" ]
#auto-format = true
formatter = { command = "bash", args = ["-c", "xmllint --format -"] }



[[language]]
name = "sql"
auto-format = true
formatter = { command = "bash", args = ["-c", "npx sql-formatter -l tsql"] }



[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
# diagnosticsTrigger = "Save"
usePlaceholders = true
staticcheck = true
vulncheck = "Imports" # or "All"
gofumpt = true

[language-server.gopls.config.analyses]
unusedfunc = true
unusedparams = true
unreachable = true
unusedvariable = true

[language-server.gopls.config.hints]
compositeLiteralTypes = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = " " }
auto-format = true
language-servers = ["gopls", "gosnippets"]

[language-server.gosnippets]
command = "bash"
args = ["-c", "snippets-ls -path $HOME/.config/helix/go.json"]



[[language]]
name = "html"
auto-format = true
file-types = ["html", "xml"]



[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = ["format"] },
  "biome",
  "tailwindcss-ls"
]
formatter = { command = "biome", args = ["format", "--stdin-file-path=_.json"] }
auto-format = true



[[language]]
name = "javascript"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
  "tailwindcss-ls",
  "jssnippets"
]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "_.js"] }
auto-format = true

[language-server.jssnippets]
command = "bash"
args = ["-c", "snippets-ls -path $HOME/.config/helix/js.json"]



[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
  "tailwindcss-ls"
]
formatter = { command = "biome", args = ["format", "--stdin-file-path=_.ts"] }
auto-format = true



[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "_.css"] }
auto-format = true


